name: widget
description: A widget library.
version: 0.0.1
homepage:

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  flutter_search_bar: ^2.1.0
  uuid: ^3.0.4
  intl: ^0.17.0
  jwt_decode: ^0.3.1
  api:
    path: ../api
    # git:
    #   url: git@bitbucket.org:devit/dart-library.git
    #   ref: master
    #   path: api

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
